import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "../assests/scss/style.css";
import Header from "../components/Header";
import Footer from "@/components/Footer";
import OfferBlock from "@/components/OfferBlock";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <Header/>
    <main className="">
      {children}
    </main>
    <Footer/>
    </body>
    </html>
  );
}
